#
development:

  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  host: 127.0.0.1
  port: 5432
  database: caled
  pool: 5
  timeout: 5000


test:
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  host: 127.0.0.1
  port: 5432
  database: calet
  pool: 5
  timeout: 5000

production:
    adapter: postgresql
    encoding: unicode
    username: postgres
    password: password
    host: 127.0.0.1
    port: 5432
    database: calep
    pool: 5
    timeout: 5000
